"""empty message

Revision ID: 09eb82743ee1
Revises: 6a1a5d56c53d
Create Date: 2024-05-08 13:02:41.347947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09eb82743ee1'
down_revision: Union[str, None] = '6a1a5d56c53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('original_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_urls_original_url'), 'urls', ['original_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_original_url'), table_name='urls')
    op.drop_column('urls', 'original_url')
    # ### end Alembic commands ###
