"""admin_url

Revision ID: 6a602e9036fc
Revises: d717675208f1
Create Date: 2024-08-02 09:47:42.508011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a602e9036fc'
down_revision: Union[str, None] = 'd717675208f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('admin_url', sa.String(), nullable=True))
    op.drop_index('ix_urls_target_url', table_name='urls')
    op.drop_index('ix_urls_shortened_url', table_name='urls')
    op.create_index(op.f('ix_urls_shortened_url'), 'urls', ['shortened_url'], unique=False)
    op.create_index(op.f('ix_urls_admin_url'), 'urls', ['admin_url'], unique=False)
    op.drop_column('urls', 'target_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('target_url', sa.TEXT(), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_urls_admin_url'), table_name='urls')
    op.drop_index(op.f('ix_urls_shortened_url'), table_name='urls')
    op.create_index('ix_urls_shortened_url', 'urls', ['shortened_url'], unique=True)
    op.create_index('ix_urls_target_url', 'urls', ['target_url'], unique=False)
    op.drop_column('urls', 'admin_url')
    # ### end Alembic commands ###
