"""empty message

Revision ID: d717675208f1
Revises: 09eb82743ee1
Create Date: 2024-05-08 19:51:25.909571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd717675208f1'
down_revision: Union[str, None] = '09eb82743ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('shortened_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_urls_shortened_url'), 'urls', ['shortened_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_shortened_url'), table_name='urls')
    op.drop_column('urls', 'shortened_url')
    # ### end Alembic commands ###
